In [ ]:
import numpy as np
import pandas as pd


In [ ]:
np.__version__

'1.19.5'

In [ ]:
pd.__version__

'1.1.5'

In [ ]:
url = "https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"

In [ ]:
data = pd.read_csv(url)
data.head()

Make       Model  Year  ... city mpg  Popularity   MSRP
0  BMW  1 Series M  2011  ...       19        3916  46135
1  BMW    1 Series  2011  ...       19        3916  40650
2  BMW    1 Series  2011  ...       20        3916  36350
3  BMW    1 Series  2011  ...       18        3916  29450
4  BMW    1 Series  2011  ...       18        3916  34500

[5 rows x 16 columns]

In [ ]:
data.shape

(11914, 16)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [ ]:
#3 Average Price of BMW Cars

data[data['Make'] == 'BMW'].MSRP.mean()

61546.76347305389

In [ ]:
#4 Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?
data[data['Year'] >= 2015]['Engine HP'].isnull().value_counts()

False    5944
True       51
Name: Engine HP, dtype: int64

In [ ]:
#5 Calculate the average "Engine HP" in the dataset.
data['Engine HP'].mean()

249.38607007176023

In [ ]:
data['Engine HP'].fillna(data['Engine HP'].mean(), inplace = True)

In [ ]:
data['Engine HP'].mean()

249.38607007176

In [ ]:
#6

In [ ]:
#7

y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

w = np.transpose(y) * np.linalg.inv(y)

LinAlgError: ignored

In [ ]:
print(w)

[[1000000 1100000  900000 1200000 1000000  850000 1300000]
 [1100000 1210000  990000 1320000 1100000  935000 1430000]
 [ 900000  990000  810000 1080000  900000  765000 1170000]
 [1200000 1320000 1080000 1440000 1200000 1020000 1560000]
 [1000000 1100000  900000 1200000 1000000  850000 1300000]
 [ 850000  935000  765000 1020000  850000  722500 1105000]
 [1300000 1430000 1170000 1560000 1300000 1105000 1690000]]
